In [1]:
import os
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
# ultime due mosse
states = np.load('ai_states.npy')
actions = np.load('ai_actions.npy')

In [3]:
print(states.shape)
print(actions.shape)

(10000, 6, 7)
(10000,)


In [4]:
states = states.reshape((-1, 6, 7, 1))

In [5]:
X_train, X_test, Y_train, Y_test = train_test_split(states, actions, test_size=0.01, random_state=123)

In [6]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(9900, 6, 7, 1)
(9900,)
(100, 6, 7, 1)
(100,)


In [8]:
from keras.models import load_model
model = load_model('my_first_model.h5')

In [10]:
from sklearn import metrics
model.fit(X_train, Y_train, epochs=100)

Epoch 1/100
9900/9900 [==============================] - 1s 67us/step - loss: 0.4539 - acc: 0.8339
Epoch 2/100
9900/9900 [==============================] - 1s 67us/step - loss: 0.4527 - acc: 0.8339
Epoch 3/100
9900/9900 [==============================] - 1s 67us/step - loss: 0.4535 - acc: 0.8343
Epoch 4/100
9900/9900 [==============================] - 1s 66us/step - loss: 0.4510 - acc: 0.8345
Epoch 5/100
9900/9900 [==============================] - 1s 69us/step - loss: 0.4508 - acc: 0.8342
Epoch 6/100
9900/9900 [==============================] - 1s 67us/step - loss: 0.4488 - acc: 0.8323
Epoch 7/100
9900/9900 [==============================] - 1s 67us/step - loss: 0.4489 - acc: 0.8321
Epoch 8/100
9900/9900 [==============================] - 1s 68us/step - loss: 0.4477 - acc: 0.8322
Epoch 9/100
9900/9900 [==============================] - 1s 67us/step - loss: 0.4477 - acc: 0.8351
Epoch 10/100
9900/9900 [==============================] - 1s 67us/step - loss: 0.4457 - acc: 0.8340
Epoch 11/

9900/9900 [==============================] - 1s 67us/step - loss: 0.4241 - acc: 0.8367
Epoch 84/100
9900/9900 [==============================] - 1s 65us/step - loss: 0.4243 - acc: 0.8371
Epoch 85/100
9900/9900 [==============================] - 1s 66us/step - loss: 0.4241 - acc: 0.8349
Epoch 86/100
9900/9900 [==============================] - 1s 66us/step - loss: 0.4229 - acc: 0.8369
Epoch 87/100
9900/9900 [==============================] - 1s 67us/step - loss: 0.4241 - acc: 0.8366
Epoch 88/100
9900/9900 [==============================] - 1s 66us/step - loss: 0.4230 - acc: 0.8357
Epoch 89/100
9900/9900 [==============================] - 1s 66us/step - loss: 0.4233 - acc: 0.8345
Epoch 90/100
9900/9900 [==============================] - 1s 66us/step - loss: 0.4233 - acc: 0.8370
Epoch 91/100
9900/9900 [==============================] - 1s 66us/step - loss: 0.4237 - acc: 0.8366
Epoch 92/100
9900/9900 [==============================] - 1s 66us/step - loss: 0.4227 - acc: 0.8376
Epoch 93/100


In [246]:
_, train_acc = model.evaluate(X_train, Y_train)
_, test_acc = model.evaluate(X_test, Y_test)
variance_train = np.var(Y_train)
variance_test = np.var(Y_test)

50/50 [==============================] - 0s 170us/step


In [247]:
Y_pred = [np.argmax(j) for j in model.predict(X_test)]
confusion_matrix = metrics.confusion_matrix(Y_test, Y_pred)
print('confusion matrix test:\n', confusion_matrix)

confusion matrix test:
 [[3 0 0 0 0 0 0]
 [0 3 2 1 1 2 0]
 [0 0 9 3 1 2 0]
 [0 1 1 5 1 2 2]
 [0 1 0 1 1 2 0]
 [0 0 1 0 0 1 0]
 [0 0 0 2 0 0 2]]


In [248]:
Y_pred = [np.argmax(j) for j in model.predict(X_train)]
confusion_matrix = metrics.confusion_matrix(Y_train, Y_pred)
print('confusion matrix train:\n', confusion_matrix)

confusion matrix train:
 [[ 377    7   19   18    2    3    0]
 [   5  548   13   29   12    9    0]
 [   3   13  747   46   15   16    2]
 [   4   11   21 1034   21   30    3]
 [   3   12   34   52  702   28    8]
 [   1    2   13   22   12  586    4]
 [   0    1    6   14    4   13  409]]


In [ ]:
from keras.models import load_model
model.save('my_first_model.h5')