In [6]:
import os
import numpy as np
from sklearn.model_selection import train_test_split

In [25]:
# tutte le partite
states = np.load('states.npy')
actions = np.load('actions.npy')

In [34]:
# ultime tre mosse
states = np.load('states_endgames.npy')
actions = np.load('actions_endgames.npy')

FileNotFoundError: [Errno 2] No such file or directory: 'states_endgames.npy'

In [140]:
# ultime due mosse
states = np.load('states_endgames2.npy')
actions = np.load('actions_endgames2.npy')

In [205]:
# solo ultima mossa
states = np.load('states_endgames3.npy')
actions = np.load('actions_endgames3.npy')

In [26]:
print(states.shape)
print(actions.shape)

(108321, 6, 7)
(108321,)


In [27]:
states = states.reshape((-1, 6, 7, 1))

In [28]:
X_train, X_test, Y_train, Y_test = train_test_split(states, actions, test_size=0.1, random_state=123)

In [29]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(97488, 6, 7, 1)
(97488,)
(10833, 6, 7, 1)
(10833,)


In [30]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Activation, Dropout, Flatten, Dense

model = Sequential()
model.add(Conv2D(16, (5, 5), input_shape=(6, 7, 1), padding='SAME'))
model.add(Activation('relu'))
#model.add(MaxPooling2D(pool_size=(2, 2)))

In [31]:
model.add(Conv2D(32, (5, 5), padding='SAME'))
model.add(Activation('relu'))
#model.add(MaxPooling2D(pool_size=(2, 2)))

In [176]:
model.add(Conv2D(32, (4, 4), padding='SAME'))
model.add(Activation('relu'))
#model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(64, (4, 4), padding='SAME'))
model.add(Activation('relu'))
#model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(64, (2, 2), padding='SAME'))
model.add(Activation('relu'))
#model.add(MaxPooling2D(pool_size=(2, 2)))

from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Activation, Dropout, Flatten, Dense

model = Sequential()
model.add(Conv2D(32, (3, 3), input_shape=(320, 256, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(128, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

In [32]:
model.add(Flatten())  # this converts our 3D feature maps to 1D feature vectors
model.add(Dense(64))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(7))
model.add(Activation('sigmoid'))

model.compile(loss='sparse_categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

In [33]:
from sklearn import metrics
model.fit(X_train, Y_train, epochs=100)

Epoch 1/100
80256/97488 [=======================>......] - ETA: 5s - loss: 1.9280 - acc: 0.1769

KeyboardInterrupt: 

In [246]:
_, train_acc = model.evaluate(X_train, Y_train)
_, test_acc = model.evaluate(X_test, Y_test)
variance_train = np.var(Y_train)
variance_test = np.var(Y_test)

50/50 [==============================] - 0s 170us/step


In [247]:
Y_pred = [np.argmax(j) for j in model.predict(X_test)]
confusion_matrix = metrics.confusion_matrix(Y_test, Y_pred)
print('confusion matrix test:\n', confusion_matrix)

confusion matrix test:
 [[3 0 0 0 0 0 0]
 [0 3 2 1 1 2 0]
 [0 0 9 3 1 2 0]
 [0 1 1 5 1 2 2]
 [0 1 0 1 1 2 0]
 [0 0 1 0 0 1 0]
 [0 0 0 2 0 0 2]]


In [248]:
Y_pred = [np.argmax(j) for j in model.predict(X_train)]
confusion_matrix = metrics.confusion_matrix(Y_train, Y_pred)
print('confusion matrix train:\n', confusion_matrix)

confusion matrix train:
 [[ 377    7   19   18    2    3    0]
 [   5  548   13   29   12    9    0]
 [   3   13  747   46   15   16    2]
 [   4   11   21 1034   21   30    3]
 [   3   12   34   52  702   28    8]
 [   1    2   13   22   12  586    4]
 [   0    1    6   14    4   13  409]]


In [ ]:
from keras.models import load_model
model.save('my_first_model.h5')